version: '3.9'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: qwerty123
      MYSQL_DATABASE: QuizzesDB
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql